name: vitamina_de_banana

on: 
  workflow_dispatch:

jobs:
  batendo_a_banana:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Liquidificador
      run: |
        tar -cvzf batida-de-banana.tar.gz banana24.html

    - name: Copia arquivo para o server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        key: ${{ secrets.SSH_KEY }}
        source: "batida-de-banana.tar.gz"
        target: /tmp